<a href="https://colab.research.google.com/github/awaiskhan005/DATA-SCIENCE-AND-AI-/blob/main/credit_card_fraud_ML_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [10]:
# prompt: import ml libraries

from sklearn import *
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("/content/sample_data/credit (1).csv")
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [4]:
y= df['default.payment.next.month']

In [5]:
# prompt: how to remove a coloumn from pandas dataframe

df.drop('default.payment.next.month', axis=1, inplace=True)
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,3,90000.0,2,2,2,34,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,4,50000.0,2,2,1,37,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0

In [8]:
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,3,90000.0,2,2,2,34,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,4,50000.0,2,2,1,37,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [11]:
X_train , X_test , y_train , y_test = train_test_split(df, y, test_size=0.2)

In [15]:
X_train

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
886,887,310000.0,1,1,2,30,-2,-2,-2,-2,...,1284.0,1088.0,892.0,-304.0,1300.0,1000.0,1000.0,1000.0,304.0,39544.0
9008,9009,560000.0,1,2,1,32,1,-2,-2,-1,...,4593.0,2512.0,11461.0,3402.0,1163.0,1023.0,2519.0,46518.0,3421.0,11467.0
11973,11974,20000.0,2,2,2,23,0,0,0,0,...,18552.0,15562.0,16308.0,17034.0,1327.0,1250.0,800.0,1000.0,1000.0,1000.0
21650,21651,30000.0,2,2,1,26,-1,-1,-1,-1,...,2730.0,1770.0,0.0,11242.0,7231.0,2732.0,1770.0,0.0,11242.0,2000.0
2062,2063,80000.0,2,2,1,30,0,0,0,0,...,9701.0,8969.0,8529.0,8737.0,3000.0,2005.0,1013.0,1000.0,350.0,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12371,12372,40000.0,2,2,1,28,1,2,2,2,...,22040.0,23396.0,20430.0,20763.0,2000.0,0.0,2000.0,0.0,1000.0,1000.0
21106,21107,80000.0,1,3,1,45,0,0,0,0,...,50209.0,43323.0,40275.0,38690.0,2019.0,2031.0,2013.0,2016.0,2002.0,3000.0
9837,9838,180000.0,2,2,1,30,0,0,0,0,...,25590.0,5817.0,13623.0,-2202.0,3000.0,6000.0,1000.0,13623.0,388.0,77001.0
4885,4886,150000.0,1,1,2,29,-1,-1,-2,-1,...,0.0,12877.0,1558.0,225.0,0.0,0.0,12877.0,1558.0,225.0,0.0
22343,22344,210000.0,2,2,2,26,0,0,0,0,...,37998.0,32062.0,27056.0,15955.0,2000.0,2200.0,2008.0,2000.0,5000.0,5000.0

In [18]:
X_train.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
dtype: int64

In [16]:
X_test

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
8783,8784,50000.0,2,2,1,34,0,0,0,0,...,24965.0,7592.0,1582.0,1099.0,1538.0,1575.0,1582.0,593.0,242.0,17012.0
26536,26537,80000.0,2,3,1,54,0,0,0,0,...,63914.0,54382.0,48834.0,49756.0,3200.0,3002.0,2202.0,2000.0,2000.0,2000.0
15675,15676,80000.0,1,2,2,24,1,-2,-2,-1,...,-1458.0,16950.0,16475.0,19284.0,0.0,3.0,18950.0,0.0,5889.0,0.0
26431,26432,50000.0,2,2,2,38,0,0,0,0,...,38272.0,29810.0,18674.0,19391.0,2511.0,2000.0,3000.0,4000.0,1000.0,1000.0
427,428,170000.0,2,1,2,31,-1,-1,-1,-1,...,199.0,398.0,199.0,199.0,199.0,199.0,398.0,0.0,199.0,398.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12844,12845,200000.0,1,1,1,30,0,0,0,0,...,124075.0,99440.0,104685.0,54038.0,4653.0,5000.0,5000.0,6000.0,5000.0,10000.0
14968,14969,20000.0,2,1,1,43,-1,-1,-1,0,...,2500.0,1000.0,0.0,0.0,4027.0,2500.0,0.0,0.0,0.0,0.0
28414,28415,130000.0,2,3,2,29,0,0,-1,-1,...,2277.0,1132.0,1289.0,0.0,1000.0,2277.0,1132.0,1289.0,0.0,2080.0
14407,14408,30000.0,2,1,2,23,2,0,0,0,...,16882.0,16911.0,17416.0,17608.0,1265.0,1577.0,606.0,778.0,630.0,653.0
21229,21230,200000.0,1,1,1,37,1,-2,-1,-1,...,250.0,4188.0,1399.0,1196.0,0.0,250.0,4188.0,0.0,0.0,0.0

In [19]:
X_test.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
dtype: int64

In [14]:

y_test

8783     0
26536    0
15675    1
26431    0
427      1
        ..
12844    0
14968    0
28414    0
14407    1
21229    0
Name: default.payment.next.month, Length: 6000, dtype: int64

In [20]:
y_test.isnull().sum()

0

In [17]:
y_train

886      0
9008     0
11973    0
21650    0
2062     0
        ..
12371    1
21106    0
9837     0
4885     0
22343    0
Name: default.payment.next.month, Length: 24000, dtype: int64