<a href="https://colab.research.google.com/github/awaiskhan005/DATA-SCIENCE-AND-AI-/blob/main/credit_card_fraud_ML_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
# prompt: import ml libraries

from sklearn import *
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("/content/sample_data/credit (1).csv")
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [5]:
y= df['default.payment.next.month']

In [6]:
# prompt: how to remove a coloumn from pandas dataframe

df.drop('default.payment.next.month', axis=1, inplace=True)
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,3,90000.0,2,2,2,34,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,4,50000.0,2,2,1,37,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0

In [7]:
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,2,120000.0,2,2,2,26,-1,2,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,3,90000.0,2,2,2,34,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,4,50000.0,2,2,1,37,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,1,3,1,39,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,29997,150000.0,1,3,2,43,-1,-1,-1,-1,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,29998,30000.0,1,2,2,37,4,3,2,-1,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,29999,80000.0,1,3,1,41,1,-1,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,30000,50000.0,1,2,1,46,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [8]:
X_train , X_test , y_train , y_test = train_test_split(df, y, test_size=0.2)

In [9]:
X_train

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
9027,9028,520000.0,1,1,2,39,-1,-1,-1,-1,...,5480.0,5397.0,70137.0,11819.0,12712.0,5487.0,5397.0,70137.0,11820.0,7888.0
1272,1273,370000.0,2,1,1,53,-1,-1,-1,-1,...,12094.0,30751.0,30131.0,9630.0,8162.0,12294.0,30751.0,30131.0,0.0,0.0
25053,25054,500000.0,1,1,1,55,3,2,2,2,...,4957.0,4957.0,4957.0,4957.0,0.0,0.0,0.0,0.0,0.0,0.0
2608,2609,20000.0,2,2,1,26,0,0,0,0,...,17705.0,19228.0,18804.0,19316.0,1300.0,1277.0,1800.0,0.0,1000.0,1000.0
6403,6404,100000.0,2,3,2,27,0,0,0,0,...,40037.0,40584.0,43629.0,41432.0,1958.0,1953.0,1500.0,3700.0,0.0,1700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22147,22148,100000.0,2,1,2,29,1,2,0,-1,...,2394.0,2839.0,32934.0,31056.0,0.0,2000.0,3000.0,31000.0,2000.0,5000.0
7753,7754,310000.0,1,2,1,44,0,0,0,0,...,7739.0,8843.0,12204.0,14520.0,2500.0,2000.0,2000.0,3500.0,2500.0,1500.0
18016,18017,20000.0,1,3,2,40,0,0,0,2,...,15657.0,14418.0,13561.0,13291.0,1238.0,2959.0,580.0,0.0,435.0,518.0
11894,11895,60000.0,1,2,1,32,0,0,0,0,...,58152.0,58615.0,54338.0,55915.0,2147.0,4740.0,1926.0,2597.0,2638.0,2478.0
24485,24486,180000.0,1,2,1,33,-2,-2,-2,-2,...,264.0,7352.0,1385.0,7880.0,3198.0,264.0,7373.0,1385.0,7880.0,0.0

In [10]:
X_train.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
dtype: int64

In [11]:
X_test

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
6322,6323,60000.0,2,3,2,40,-1,-1,0,0,...,15219.0,16158.0,14295.0,10930.0,20391.0,1200.0,3658.0,0.0,10930.0,11677.0
12711,12712,250000.0,2,1,1,35,0,0,0,0,...,71488.0,69145.0,68680.0,70047.0,3500.0,3070.0,2372.0,2413.0,2428.0,2507.0
21720,21721,20000.0,2,2,2,21,0,0,0,0,...,17850.0,13560.0,11748.0,10632.0,1318.0,1499.0,1099.0,333.0,2000.0,2000.0
19818,19819,30000.0,2,3,1,42,0,0,0,2,...,27851.0,27098.0,29866.0,29276.0,1706.0,5251.0,0.0,3519.0,0.0,1368.0
25953,25954,150000.0,2,1,1,45,-2,-2,-2,-2,...,14279.0,5985.0,8333.0,8241.0,4133.0,14296.0,5990.0,8342.0,8241.0,17817.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29143,29144,200000.0,2,1,1,52,-1,-1,-1,-1,...,1169.0,3175.0,153.0,0.0,317.0,1169.0,3178.0,153.0,0.0,0.0
18787,18788,50000.0,2,1,2,28,0,0,0,0,...,36700.0,37319.0,37633.0,40307.0,2100.0,2000.0,1700.0,1307.0,3400.0,1500.0
27101,27102,300000.0,1,2,1,45,1,-1,0,0,...,236220.0,233586.0,234661.0,233304.0,244500.0,8613.0,8000.0,11000.0,8093.0,6399.0
14732,14733,340000.0,2,2,2,43,0,0,2,0,...,113312.0,114379.0,113627.0,112193.0,12002.0,0.0,4387.0,4634.0,4519.0,2402.0
9025,9026,20000.0,1,1,2,25,0,0,0,0,...,17839.0,18040.0,18414.0,16213.0,1595.0,1551.0,752.0,773.0,772.0,354.0

In [12]:
X_test.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
dtype: int64

In [13]:

y_test

6322     0
12711    0
21720    0
19818    1
25953    0
        ..
29143    0
18787    0
27101    1
14732    0
9025     0
Name: default.payment.next.month, Length: 6000, dtype: int64

In [14]:
y_test.isnull().sum()

0

In [15]:
y_train

9027     0
1272     0
25053    1
2608     1
6403     1
        ..
22147    0
7753     0
18016    0
11894    0
24485    0
Name: default.payment.next.month, Length: 24000, dtype: int64

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create a logistic regression model
model = LogisticRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Predict the labels for the test data
y_pred = model.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Print the confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

# Print the classification report
print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.7748333333333334
Confusion Matrix:
[[4649    0]
 [1351    0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      4649
           1       0.00      0.00      0.00      1351

    accuracy                           0.77      6000
   macro avg       0.39      0.50      0.44      6000
weighted avg       0.60      0.77      0.68      6000

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [17]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.7748333333333334