<a href="https://colab.research.google.com/github/awaiskhan005/DATA-SCIENCE-AND-AI-/blob/main/PUNJAB_AQI_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
weekly = pd.read_csv('/content/sample_data/weekly_composite_data_all.csv')

In [4]:
weekly.head()

,B1,B11,B12,B2,B3,B4,B5,B6,B7,B8,...,u_component_of_wind_10m,v_component_of_wind_10m,.geo,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,location_id
0,6702.166667,4184.833333,3352.833333,6946.833333,6242.333333,5409.500000,5946.833333,6264.833333,6212.000000,6707.166667,...,-1.205292,-1.109796,"{""type"":""Point"",""coordinates"":[71.879210723593...",NaN,NaN,NaN,NaN,NaN,NaN,1
1,444.000000,1860.000000,863.000000,671.000000,1338.000000,553.000000,1818.000000,5611.000000,6788.000000,6592.000000,...,0.579760,-0.133180,"{""type"":""Point"",""coordinates"":[74.699502957877...",NaN,NaN,NaN,NaN,NaN,NaN,2
2,80.000000,1918.000000,1001.000000,362.666667,718.333333,492.666667,1038.666667,2976.000000,3832.333333,3601.666667,...,-0.329383,0.342376,"{""type"":""Point"",""coordinates"":[73.675742406117...",NaN,NaN,NaN,NaN,NaN,NaN,3
3,13565.500000,2380.000000,2285.500000,11960.500000,10045.000000,8729.000000,9020.500000,8365.500000,7926.500000,8052.000000,...,0.321113,-0.045187,"{""type"":""Point"",""coordinates"":[73.188237806146...",NaN,NaN,NaN,NaN,NaN,NaN,4
4,15966.000000,6812.000000,5646.000000,12670.000000,10842.000000,9658.000000,10042.000000,9302.000000,8686.000000,8516.000000,...,-0.299754,-0.809324,"{""type"":""Point"",""coordinates"":[70.431848949059...",NaN,NaN,NaN,NaN,NaN,NaN,5

In [5]:
weekly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9900 entries, 0 to 9899
Data columns (total 38 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   B1                                                     9322 non-null   float64
 1   B11                                                    9323 non-null   float64
 2   B12                                                    9323 non-null   float64
 3   B2                                                     9319 non-null   float64
 4   B3                                                     9323 non-null   float64
 5   B4                                                     9323 non-null   float64
 6   B5                                                     9323 non-null   float64
 7   B6                                                     9323 non-null   float64
 8   B7                                                     9323 non-null   float64
 9   B8                                                     9323 non-null   float64
 10  B8A                                                    9323 non-null   float64
 11  B9                                                     9323 non-null   float64
 12  CH4_column_volume_mixing_ratio_dry_air_bias_corrected  7077 non-null   float64
 13  CO_column_number_density                               9496 non-null   float64
 14  Latitude                                               9900 non-null   float64
 15  Longitude                                              9900 non-null   float64
 16  NO2_column_number_density                              9636 non-null   float64
 17  O3_column_number_density                               9636 non-null   float64
 18  SO2_column_number_density                              9196 non-null   float64
 19  Week_Start_Date                                        9900 non-null   object
 20  Year                                                   9900 non-null   int64
 21  absorbing_aerosol_index                                9195 non-null   float64
 22  cloud_fraction                                         9196 non-null   float64
 23  id                                                     9900 non-null   int64
 24  latitude                                               9900 non-null   float64
 25  longitude                                              9900 non-null   float64
 26  temperature_2m                                         9636 non-null   float64
 27  tropospheric_HCHO_column_number_density                9351 non-null   float64
 28  u_component_of_wind_10m                                9636 non-null   float64
 29  v_component_of_wind_10m                                9636 non-null   float64
 30  .geo                                                   9900 non-null   object
 31  Unnamed: 31                                            0 non-null      float64
 32  Unnamed: 32                                            0 non-null      float64
 33  Unnamed: 33                                            0 non-null      float64
 34  Unnamed: 34                                            0 non-null      float64
 35  Unnamed: 35                                            0 non-null      float64
 36  Unnamed: 36                                            0 non-null      float64
 37  location_id                                            9900 non-null   int64
dtypes: float64(33), int64(3), object(2)
memory usage: 2.9+ MB

In [6]:
weekly.describe()

,B1,B11,B12,B2,B3,B4,B5,B6,B7,B8,...,tropospheric_HCHO_column_number_density,u_component_of_wind_10m,v_component_of_wind_10m,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,location_id
count,9322.000000,9323.000000,9323.000000,9319.000000,9323.000000,9323.000000,9323.000000,9323.000000,9323.000000,9323.000000,...,9351.000000,9636.000000,9636.000000,0.0,0.0,0.0,0.0,0.0,0.0,9900.000000
mean,2706.323522,3036.405793,2493.621774,2650.180815,2793.858773,2827.110096,3218.274920,3663.399482,3856.198649,3880.967792,...,0.000167,-0.127589,-0.693407,NaN,NaN,NaN,NaN,NaN,NaN,150.500000
std,3842.826598,1510.612603,1303.423602,3327.679483,2951.363335,2733.354671,2769.935054,2432.468606,2317.698818,2290.293640,...,0.000083,0.745534,0.727981,NaN,NaN,NaN,NaN,NaN,NaN,86.606433
min,0.000000,0.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.000419,-2.725808,-3.167348,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,546.125000,2018.916667,1496.000000,719.250000,1033.333333,1125.666667,1524.000000,2262.500000,2466.666667,2510.000000,...,0.000115,-0.554539,-1.187121,NaN,NaN,NaN,NaN,NaN,NaN,75.750000
50%,993.000000,2648.000000,2272.500000,1247.000000,1635.500000,1887.000000,2189.500000,2734.000000,3003.500000,3040.000000,...,0.000163,-0.075929,-0.717847,NaN,NaN,NaN,NaN,NaN,NaN,150.500000
75%,3209.250000,3548.000000,3191.000000,3109.750000,3138.250000,3140.750000,3474.333333,3926.166667,4263.750000,4326.250000,...,0.000216,0.366218,-0.207837,NaN,NaN,NaN,NaN,NaN,NaN,225.250000
max,31767.000000,10079.500000,8492.500000,31688.000000,31152.000000,24232.000000,24768.000000,23156.000000,20879.000000,20308.000000,...,0.000709,2.817224,2.376966,NaN,NaN,NaN,NaN,NaN,NaN,300.000000

In [7]:
weekly.shape

(9900, 38)

In [8]:
weekly

,B1,B11,B12,B2,B3,B4,B5,B6,B7,B8,...,u_component_of_wind_10m,v_component_of_wind_10m,.geo,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,location_id
0,6702.166667,4184.833333,3352.833333,6946.833333,6242.333333,5409.500000,5946.833333,6264.833333,6212.000000,6707.166667,...,-1.205292,-1.109796,"{""type"":""Point"",""coordinates"":[71.879210723593...",NaN,NaN,NaN,NaN,NaN,NaN,1
1,444.000000,1860.000000,863.000000,671.000000,1338.000000,553.000000,1818.000000,5611.000000,6788.000000,6592.000000,...,0.579760,-0.133180,"{""type"":""Point"",""coordinates"":[74.699502957877...",NaN,NaN,NaN,NaN,NaN,NaN,2
2,80.000000,1918.000000,1001.000000,362.666667,718.333333,492.666667,1038.666667,2976.000000,3832.333333,3601.666667,...,-0.329383,0.342376,"{""type"":""Point"",""coordinates"":[73.675742406117...",NaN,NaN,NaN,NaN,NaN,NaN,3
3,13565.500000,2380.000000,2285.500000,11960.500000,10045.000000,8729.000000,9020.500000,8365.500000,7926.500000,8052.000000,...,0.321113,-0.045187,"{""type"":""Point"",""coordinates"":[73.188237806146...",NaN,NaN,NaN,NaN,NaN,NaN,4
4,15966.000000,6812.000000,5646.000000,12670.000000,10842.000000,9658.000000,10042.000000,9302.000000,8686.000000,8516.000000,...,-0.299754,-0.809324,"{""type"":""Point"",""coordinates"":[70.431848949059...",NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9895,609.000000,2844.000000,2407.000000,808.000000,1174.000000,1308.000000,1742.000000,2219.000000,2409.000000,2598.000000,...,1.928731,-1.434920,"{""type"":""Point"",""coordinates"":[73.120169628565...",NaN,NaN,NaN,NaN,NaN,NaN,296
9896,596.000000,2863.500000,2518.500000,980.000000,1339.500000,1719.500000,1997.000000,2113.000000,2298.000000,2347.000000,...,0.121341,-0.652959,"{""type"":""Point"",""coordinates"":[70.983319353642...",NaN,NaN,NaN,NaN,NaN,NaN,297
9897,552.000000,1990.500000,1510.000000,639.500000,982.500000,1131.500000,1542.000000,2147.000000,2464.000000,2300.500000,...,-0.291745,-0.257805,"{""type"":""Point"",""coordinates"":[72.061494315557...",NaN,NaN,NaN,NaN,NaN,NaN,298
9898,709.000000,3213.000000,2928.000000,878.000000,1168.000000,1519.000000,1827.000000,1960.000000,2118.000000,2161.000000,...,-0.179011,-1.267263,"{""type"":""Point"",""coordinates"":[71.275386013542...",NaN,NaN,NaN,NaN,NaN,NaN,299
9899,606.000000,3374.000000,3110.500000,1295.500000,1710.500000,2184.000000,2433.000000,2510.000000,2702.500000,2792.500000,...,-0.002738,-1.837900,"{""type"":""Point"",""coordinates"":[71.322215492805...",NaN,NaN,NaN,NaN,NaN,NaN,300

In [9]:
weekly.isnull().sum()

B1                                                        578
B11                                                       577
B12                                                       577
B2                                                        581
B3                                                        577
B4                                                        577
B5                                                        577
B6                                                        577
B7                                                        577
B8                                                        577
B8A                                                       577
B9                                                        577
CH4_column_volume_mixing_ratio_dry_air_bias_corrected    2823
CO_column_number_density                                  404
Latitude                                                    0
Longitude                                                   0
NO2_column_number_density                                 264
O3_column_number_density                                  264
SO2_column_number_density                                 704
Week_Start_Date                                             0
Year                                                        0
absorbing_aerosol_index                                   705
cloud_fraction                                            704
id                                                          0
latitude                                                    0
longitude                                                   0
temperature_2m                                            264
tropospheric_HCHO_column_number_density                   549
u_component_of_wind_10m                                   264
v_component_of_wind_10m                                   264
.geo                                                        0
Unnamed: 31                                              9900
Unnamed: 32                                              9900
Unnamed: 33                                              9900
Unnamed: 34                                              9900
Unnamed: 35                                              9900
Unnamed: 36                                              9900
location_id                                                 0
dtype: int64

In [10]:
df = pd.read_csv('/content/sample_data/locations.csv')

In [11]:
df

      id   latitude  longitude
0      1  32.030100  71.879210
1      2  32.361531  74.699502
2      3  30.257478  73.675744
3      4  33.271899  73.188238
4      5  30.399851  70.431850
..   ...        ...        ...
295  296  33.086954  73.120171
296  297  29.251913  70.983320
297  298  30.473824  72.061493
298  299  32.798478  71.275385
299  300  32.224554  71.322217

[300 rows x 3 columns]

In [12]:
merg0 = pd.read_csv('/content/sample_data/merg0.csv')

In [13]:
merg0

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust,latitude,longitude,location_id
0,11/22/2023 0:00,82.4,53.7,435,2.5,4.4,48,5,27.8894167,71.37526358,39
1,11/22/2023 1:00,79.6,51.8,430,2.7,3.9,43,4,27.8894167,71.37526358,39
2,11/22/2023 2:00,77.8,50.6,423,3,3.2,37,4,27.8894167,71.37526358,39
3,11/22/2023 3:00,75.9,49.5,424,3,3.5,40,4,27.8894167,71.37526358,39
4,11/22/2023 4:00,81.3,52.7,443,2.3,5.7,62,6,27.8894167,71.37526358,39
...,...,...,...,...,...,...,...,...,...,...,...
386494,4/30/2024 19:00,21.7,13.3,270,9.7,2.6,70,9,33.40743947,72.39115291,63
386495,4/30/2024 20:00,19.6,12.2,280,10.4,2.6,64,7,33.40743947,72.39115291,63
386496,4/30/2024 21:00,19,12,294,11.8,2.7,58,6,33.40743947,72.39115291,63
386497,4/30/2024 22:00,19.1,12.2,313,14.8,2.8,49,5,33.40743947,72.39115291,63
386498,4/30/2024 23:00,19.9,12.8,336,18.5,2.9,40,5,33.40743947,72.39115291,63

In [20]:
merged_data = pd.merge(df, weekly, on=["location_id"])

KeyError: 'location_id'