<a href="https://colab.research.google.com/github/awaiskhan005/DATA-SCIENCE-AND-AI-/blob/main/PUNJAB_AQI_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [74]:
import pandas as pd

# Load the hourly datasets
hourly_data1 = pd.read_csv('/content/sample_data/merg0.csv')
hourly_data2 = pd.read_csv('/content/sample_data/merg1.csv')
hourly_data3 = pd.read_csv('/content/sample_data/merg2.csv')

# Load the weekly dataset
weekly_data = pd.read_csv('/content/sample_data/weekly_composite_data_all.csv')

In [75]:
hourly_data1.isnull().sum()

date                0
pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dust                0
latitude            0
longitude           0
location_id         0
dtype: int64

In [76]:
hourly_data2.isnull().sum()

date                0
pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dust                0
latitude            0
longitude           1
location_id         1
dtype: int64

In [78]:
hourly_data2.fillna(0, inplace=True)

In [79]:
hourly_data2.isnull().sum()

date                0
pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dust                0
latitude            0
longitude           0
location_id         0
dtype: int64

In [80]:
hourly_data3.isnull().sum()

date                0
pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dust                0
latitude            0
longitude           1
location_id         1
dtype: int64

In [81]:
hourly_data3.fillna(0, inplace=True)

In [82]:
# Combine hourly datasets
hourly_data = pd.concat([hourly_data1, hourly_data2, hourly_data3], ignore_index=True)

In [83]:
hourly_data

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust,latitude,longitude,location_id
0,11/22/2023 0:00,82.4,53.7,435,2.5,4.4,48,5,27.8894167,71.37526358,39
1,11/22/2023 1:00,79.6,51.8,430,2.7,3.9,43,4,27.8894167,71.37526358,39
2,11/22/2023 2:00,77.8,50.6,423,3,3.2,37,4,27.8894167,71.37526358,39
3,11/22/2023 3:00,75.9,49.5,424,3,3.5,40,4,27.8894167,71.37526358,39
4,11/22/2023 4:00,81.3,52.7,443,2.3,5.7,62,6,27.8894167,71.37526358,39
...,...,...,...,...,...,...,...,...,...,...,...
130874,12/29/2023 7:00,66.6,44.7,665,3.3,8.3,111,2,28.83060786,70.32776887,279
130875,12/29/2023 8:00,60.3,40.4,542,2.2,8.5,126,3,28.83060786,70.32776887,279
130876,12/29/2023 9:00,56.3,37.6,467,2.1,8.6,134,3,28.83060786,70.32776887,279
130877,12/29/2023 10:00,54.6,36.4,454,3.1,8.4,130,3,28.83060786,70.32776887,279
130878,12/29/2023 11:00,54.8,36.7,489,5.2,8.1,119,2,28.83060786,0,0

In [87]:
# Ensure the 'Week_Start_Date' is a datetime object
weekly_data['Week_Start_Date'] = pd.to_datetime(weekly_data['Week_Start_Date'])

In [88]:
weekly_data

,B1,B11,B12,B2,B3,B4,B5,B6,B7,B8,...,u_component_of_wind_10m,v_component_of_wind_10m,.geo,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,location_id
0,6702.166667,4184.833333,3352.833333,6946.833333,6242.333333,5409.500000,5946.833333,6264.833333,6212.000000,6707.166667,...,-1.205292,-1.109796,"{""type"":""Point"",""coordinates"":[71.879210723593...",NaN,NaN,NaN,NaN,NaN,NaN,1
1,444.000000,1860.000000,863.000000,671.000000,1338.000000,553.000000,1818.000000,5611.000000,6788.000000,6592.000000,...,0.579760,-0.133180,"{""type"":""Point"",""coordinates"":[74.699502957877...",NaN,NaN,NaN,NaN,NaN,NaN,2
2,80.000000,1918.000000,1001.000000,362.666667,718.333333,492.666667,1038.666667,2976.000000,3832.333333,3601.666667,...,-0.329383,0.342376,"{""type"":""Point"",""coordinates"":[73.675742406117...",NaN,NaN,NaN,NaN,NaN,NaN,3
3,13565.500000,2380.000000,2285.500000,11960.500000,10045.000000,8729.000000,9020.500000,8365.500000,7926.500000,8052.000000,...,0.321113,-0.045187,"{""type"":""Point"",""coordinates"":[73.188237806146...",NaN,NaN,NaN,NaN,NaN,NaN,4
4,15966.000000,6812.000000,5646.000000,12670.000000,10842.000000,9658.000000,10042.000000,9302.000000,8686.000000,8516.000000,...,-0.299754,-0.809324,"{""type"":""Point"",""coordinates"":[70.431848949059...",NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9895,609.000000,2844.000000,2407.000000,808.000000,1174.000000,1308.000000,1742.000000,2219.000000,2409.000000,2598.000000,...,1.928731,-1.434920,"{""type"":""Point"",""coordinates"":[73.120169628565...",NaN,NaN,NaN,NaN,NaN,NaN,296
9896,596.000000,2863.500000,2518.500000,980.000000,1339.500000,1719.500000,1997.000000,2113.000000,2298.000000,2347.000000,...,0.121341,-0.652959,"{""type"":""Point"",""coordinates"":[70.983319353642...",NaN,NaN,NaN,NaN,NaN,NaN,297
9897,552.000000,1990.500000,1510.000000,639.500000,982.500000,1131.500000,1542.000000,2147.000000,2464.000000,2300.500000,...,-0.291745,-0.257805,"{""type"":""Point"",""coordinates"":[72.061494315557...",NaN,NaN,NaN,NaN,NaN,NaN,298
9898,709.000000,3213.000000,2928.000000,878.000000,1168.000000,1519.000000,1827.000000,1960.000000,2118.000000,2161.000000,...,-0.179011,-1.267263,"{""type"":""Point"",""coordinates"":[71.275386013542...",NaN,NaN,NaN,NaN,NaN,NaN,299
9899,606.000000,3374.000000,3110.500000,1295.500000,1710.500000,2184.000000,2433.000000,2510.000000,2702.500000,2792.500000,...,-0.002738,-1.837900,"{""type"":""Point"",""coordinates"":[71.322215492805...",NaN,NaN,NaN,NaN,NaN,NaN,300

In [89]:
location = pd.read_csv('/content/sample_data/locations.csv')

In [95]:
weekly_data.isnull().sum()

B1                                                        578
B11                                                       577
B12                                                       577
B2                                                        581
B3                                                        577
B4                                                        577
B5                                                        577
B6                                                        577
B7                                                        577
B8                                                        577
B8A                                                       577
B9                                                        577
CH4_column_volume_mixing_ratio_dry_air_bias_corrected    2823
CO_column_number_density                                  404
Latitude                                                    0
Longitude                                                   0
NO2_column_number_density                                 264
O3_column_number_density                                  264
SO2_column_number_density                                 704
Week_Start_Date                                             0
Year                                                        0
absorbing_aerosol_index                                   705
cloud_fraction                                            704
id                                                          0
latitude                                                    0
longitude                                                   0
temperature_2m                                            264
tropospheric_HCHO_column_number_density                   549
u_component_of_wind_10m                                   264
v_component_of_wind_10m                                   264
.geo                                                        0
Unnamed: 31                                              9900
Unnamed: 32                                              9900
Unnamed: 33                                              9900
Unnamed: 34                                              9900
Unnamed: 35                                              9900
Unnamed: 36                                              9900
location_id                                                 0
dtype: int64

In [96]:
# prompt: fillna weekly dtatast

weekly_data.fillna(0, inplace=True)

In [97]:
weekly_data.isnull().sum()

B1                                                       0
B11                                                      0
B12                                                      0
B2                                                       0
B3                                                       0
B4                                                       0
B5                                                       0
B6                                                       0
B7                                                       0
B8                                                       0
B8A                                                      0
B9                                                       0
CH4_column_volume_mixing_ratio_dry_air_bias_corrected    0
CO_column_number_density                                 0
Latitude                                                 0
Longitude                                                0
NO2_column_number_density                                0
O3_column_number_density                                 0
SO2_column_number_density                                0
Week_Start_Date                                          0
Year                                                     0
absorbing_aerosol_index                                  0
cloud_fraction                                           0
id                                                       0
latitude                                                 0
longitude                                                0
temperature_2m                                           0
tropospheric_HCHO_column_number_density                  0
u_component_of_wind_10m                                  0
v_component_of_wind_10m                                  0
.geo                                                     0
Unnamed: 31                                              0
Unnamed: 32                                              0
Unnamed: 33                                              0
Unnamed: 34                                              0
Unnamed: 35                                              0
Unnamed: 36                                              0
location_id                                              0
dtype: int64

In [91]:
hourly_data = pd.concat([hourly_data, location], ignore_index=True)

In [100]:
hourly_data

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust,latitude,longitude,location_id,id
0,11/22/2023 0:00,82.4,53.7,435,2.5,4.4,48,5,27.8894167,71.37526358,39,NaN
1,11/22/2023 1:00,79.6,51.8,430,2.7,3.9,43,4,27.8894167,71.37526358,39,NaN
2,11/22/2023 2:00,77.8,50.6,423,3,3.2,37,4,27.8894167,71.37526358,39,NaN
3,11/22/2023 3:00,75.9,49.5,424,3,3.5,40,4,27.8894167,71.37526358,39,NaN
4,11/22/2023 4:00,81.3,52.7,443,2.3,5.7,62,6,27.8894167,71.37526358,39,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
131174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.086954,73.120171,NaN,296.0
131175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.251913,70.98332,NaN,297.0
131176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.473824,72.061493,NaN,298.0
131177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.798478,71.275385,NaN,299.0
131178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.224554,71.322217,NaN,300.0

In [104]:
weekly_data = pd.concat([weekly_data, location], ignore_index=True)

In [105]:
weekly_data

,B1,B11,B12,B2,B3,B4,B5,B6,B7,B8,...,u_component_of_wind_10m,v_component_of_wind_10m,.geo,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,location_id
0,6702.166667,4184.833333,3352.833333,6946.833333,6242.333333,5409.500000,5946.833333,6264.833333,6212.000000,6707.166667,...,-1.205292,-1.109796,"{""type"":""Point"",""coordinates"":[71.879210723593...",0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,444.000000,1860.000000,863.000000,671.000000,1338.000000,553.000000,1818.000000,5611.000000,6788.000000,6592.000000,...,0.579760,-0.133180,"{""type"":""Point"",""coordinates"":[74.699502957877...",0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,80.000000,1918.000000,1001.000000,362.666667,718.333333,492.666667,1038.666667,2976.000000,3832.333333,3601.666667,...,-0.329383,0.342376,"{""type"":""Point"",""coordinates"":[73.675742406117...",0.0,0.0,0.0,0.0,0.0,0.0,3.0
3,13565.500000,2380.000000,2285.500000,11960.500000,10045.000000,8729.000000,9020.500000,8365.500000,7926.500000,8052.000000,...,0.321113,-0.045187,"{""type"":""Point"",""coordinates"":[73.188237806146...",0.0,0.0,0.0,0.0,0.0,0.0,4.0
4,15966.000000,6812.000000,5646.000000,12670.000000,10842.000000,9658.000000,10042.000000,9302.000000,8686.000000,8516.000000,...,-0.299754,-0.809324,"{""type"":""Point"",""coordinates"":[70.431848949059...",0.0,0.0,0.0,0.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
weekly_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 38 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   B1                                                     9900 non-null   float64
 1   B11                                                    9900 non-null   float64
 2   B12                                                    9900 non-null   float64
 3   B2                                                     9900 non-null   float64
 4   B3                                                     9900 non-null   float64
 5   B4                                                     9900 non-null   float64
 6   B5                                                     9900 non-null   float64
 7   B6                                                     9900 non-null   float64
 8   B7                                                     9900 non-null   float64
 9   B8                                                     9900 non-null   float64
 10  B8A                                                    9900 non-null   float64
 11  B9                                                     9900 non-null   float64
 12  CH4_column_volume_mixing_ratio_dry_air_bias_corrected  9900 non-null   float64
 13  CO_column_number_density                               9900 non-null   float64
 14  Latitude                                               9900 non-null   float64
 15  Longitude                                              9900 non-null   float64
 16  NO2_column_number_density                              9900 non-null   float64
 17  O3_column_number_density                               9900 non-null   float64
 18  SO2_column_number_density                              9900 non-null   float64
 19  Week_Start_Date                                        9900 non-null   datetime64[ns]
 20  Year                                                   9900 non-null   float64
 21  absorbing_aerosol_index                                9900 non-null   float64
 22  cloud_fraction                                         9900 non-null   float64
 23  id                                                     10200 non-null  int64
 24  latitude                                               10200 non-null  float64
 25  longitude                                              10200 non-null  float64
 26  temperature_2m                                         9900 non-null   float64
 27  tropospheric_HCHO_column_number_density                9900 non-null   float64
 28  u_component_of_wind_10m                                9900 non-null   float64
 29  v_component_of_wind_10m                                9900 non-null   float64
 30  .geo                                                   9900 non-null   object
 31  Unnamed: 31                                            9900 non-null   float64
 32  Unnamed: 32                                            9900 non-null   float64
 33  Unnamed: 33                                            9900 non-null   float64
 34  Unnamed: 34                                            9900 non-null   float64
 35  Unnamed: 35                                            9900 non-null   float64
 36  Unnamed: 36                                            9900 non-null   float64
 37  location_id                                            9900 non-null   float64
dtypes: datetime64[ns](1), float64(35), int64(1), object(1)
memory usage: 3.0+ MB

In [107]:
weekly_data.isnull().sum()

B1                                                       300
B11                                                      300
B12                                                      300
B2                                                       300
B3                                                       300
B4                                                       300
B5                                                       300
B6                                                       300
B7                                                       300
B8                                                       300
B8A                                                      300
B9                                                       300
CH4_column_volume_mixing_ratio_dry_air_bias_corrected    300
CO_column_number_density                                 300
Latitude                                                 300
Longitude                                                300
NO2_column_number_density                                300
O3_column_number_density                                 300
SO2_column_number_density                                300
Week_Start_Date                                          300
Year                                                     300
absorbing_aerosol_index                                  300
cloud_fraction                                           300
id                                                         0
latitude                                                   0
longitude                                                  0
temperature_2m                                           300
tropospheric_HCHO_column_number_density                  300
u_component_of_wind_10m                                  300
v_component_of_wind_10m                                  300
.geo                                                     300
Unnamed: 31                                              300
Unnamed: 32                                              300
Unnamed: 33                                              300
Unnamed: 34                                              300
Unnamed: 35                                              300
Unnamed: 36                                              300
location_id                                              300
dtype: int64

In [108]:
weekly_data.fillna(0, inplace=True)

In [130]:
hourly_data

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust,latitude,longitude,location_id,id
0,11/22/2023 0:00,82.4,53.7,435,2.5,4.4,48,5,27.8894167,71.37526358,39,NaN
1,11/22/2023 1:00,79.6,51.8,430,2.7,3.9,43,4,27.8894167,71.37526358,39,NaN
2,11/22/2023 2:00,77.8,50.6,423,3,3.2,37,4,27.8894167,71.37526358,39,NaN
3,11/22/2023 3:00,75.9,49.5,424,3,3.5,40,4,27.8894167,71.37526358,39,NaN
4,11/22/2023 4:00,81.3,52.7,443,2.3,5.7,62,6,27.8894167,71.37526358,39,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
131174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.086954,73.120171,NaN,296.0
131175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.251913,70.98332,NaN,297.0
131176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.473824,72.061493,NaN,298.0
131177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.798478,71.275385,NaN,299.0
131178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.224554,71.322217,NaN,300.0

In [131]:
weekly_data

,B1,B11,B12,B2,B3,B4,B5,B6,B7,B8,...,u_component_of_wind_10m,v_component_of_wind_10m,.geo,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,location_id
0,6702.166667,4184.833333,3352.833333,6946.833333,6242.333333,5409.500000,5946.833333,6264.833333,6212.000000,6707.166667,...,-1.205292,-1.109796,"{""type"":""Point"",""coordinates"":[71.879210723593...",0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,444.000000,1860.000000,863.000000,671.000000,1338.000000,553.000000,1818.000000,5611.000000,6788.000000,6592.000000,...,0.579760,-0.133180,"{""type"":""Point"",""coordinates"":[74.699502957877...",0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,80.000000,1918.000000,1001.000000,362.666667,718.333333,492.666667,1038.666667,2976.000000,3832.333333,3601.666667,...,-0.329383,0.342376,"{""type"":""Point"",""coordinates"":[73.675742406117...",0.0,0.0,0.0,0.0,0.0,0.0,3.0
3,13565.500000,2380.000000,2285.500000,11960.500000,10045.000000,8729.000000,9020.500000,8365.500000,7926.500000,8052.000000,...,0.321113,-0.045187,"{""type"":""Point"",""coordinates"":[73.188237806146...",0.0,0.0,0.0,0.0,0.0,0.0,4.0
4,15966.000000,6812.000000,5646.000000,12670.000000,10842.000000,9658.000000,10042.000000,9302.000000,8686.000000,8516.000000,...,-0.299754,-0.809324,"{""type"":""Point"",""coordinates"":[70.431848949059...",0.0,0.0,0.0,0.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10196,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10197,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10198,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10199,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [132]:
X = hourly_data.drop(['carbon_monoxide'], axis=1)
y = hourly_data['carbon_monoxide']