<a href="https://colab.research.google.com/github/awaiskhan005/DATA-SCIENCE-AND-AI-/blob/main/Untitled46.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1 = pd.read_csv('/content/sample_data/WTI_monthly_spotprice.xlsx')
df2 = pd.read_csv('/content/sample_data/INDPRO.xlsx')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 16: invalid continuation byte

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_excel('/content/sample_data/WTI_monthly_spotprice.xlsx') # Use read_excel for excel files
df2 = pd.read_excel('/content/sample_data/INDPRO.xlsx') # Use read_excel for excel files

In [4]:
df1.head()

        Date  Spot Price
0 1986-01-15       22.93
1 1986-02-15       15.46
2 1986-03-15       12.61
3 1986-04-15       12.84
4 1986-05-15       15.38

In [8]:
# prompt: show the whole data of df1

df1

          Date  Spot Price
0   1986-01-15       22.93
1   1986-02-15       15.46
2   1986-03-15       12.61
3   1986-04-15       12.84
4   1986-05-15       15.38
..         ...         ...
458 2024-03-15       81.28
459 2024-04-15       85.35
460 2024-05-15       80.02
461 2024-06-15       79.77
462 2024-07-15       81.80

[463 rows x 2 columns]

In [9]:
# prompt: show full rows of df1

pd.set_option('display.max_rows', None)
df1

          Date  Spot Price
0   1986-01-15       22.93
1   1986-02-15       15.46
2   1986-03-15       12.61
3   1986-04-15       12.84
4   1986-05-15       15.38
5   1986-06-15       13.43
6   1986-07-15       11.59
7   1986-08-15       15.10
8   1986-09-15       14.87
9   1986-10-15       14.90
10  1986-11-15       15.22
11  1986-12-15       16.11
12  1987-01-15       18.65
13  1987-02-15       17.75
14  1987-03-15       18.30
15  1987-04-15       18.68
16  1987-05-15       19.44
17  1987-06-15       20.07
18  1987-07-15       21.34
19  1987-08-15       20.31
20  1987-09-15       19.53
21  1987-10-15       19.86
22  1987-11-15       18.85
23  1987-12-15       17.28
24  1988-01-15       17.13
25  1988-02-15       16.80
26  1988-03-15       16.20
27  1988-04-15       17.86
28  1988-05-15       17.42
29  1988-06-15       16.53
30  1988-07-15       15.50
31  1988-08-15       15.52
32  1988-09-15       14.54
33  1988-10-15       13.77
34  1988-11-15       14.14
35  1988-12-15       16.38
36  1989-01-15       18.02
37  1989-02-15       17.94
38  1989-03-15       19.48
39  1989-04-15       21.07
40  1989-05-15       20.12
41  1989-06-15       20.05
42  1989-07-15       19.78
43  1989-08-15       18.58
44  1989-09-15       19.59
45  1989-10-15       20.10
46  1989-11-15       19.86
47  1989-12-15       21.10
48  1990-01-15       22.86
49  1990-02-15       22.11
50  1990-03-15       20.39
51  1990-04-15       18.43
52  1990-05-15       18.20
53  1990-06-15       16.70
54  1990-07-15       18.45
55  1990-08-15       27.31
56  1990-09-15       33.51
57  1990-10-15       36.04
58  1990-11-15       32.33
59  1990-12-15       27.28
60  1991-01-15       25.23
61  1991-02-15       20.48
62  1991-03-15       19.90
63  1991-04-15       20.83
64  1991-05-15       21.23
65  1991-06-15       20.19
66  1991-07-15       21.40
67  1991-08-15       21.69
68  1991-09-15       21.89
69  1991-10-15       23.23
70  1991-11-15       22.46
71  1991-12-15       19.50
72  1992-01-15       18.79
73  1992-02-15       19.01
74  1992-03-15       18.92
75  1992-04-15       20.23
76  1992-05-15       20.98
77  1992-06-15       22.39
78  1992-07-15       21.78
79  1992-08-15       21.34
80  1992-09-15       21.88
81  1992-10-15       21.69
82  1992-11-15       20.34
83  1992-12-15       19.41
84  1993-01-15       19.03
85  1993-02-15       20.09
86  1993-03-15       20.32
87  1993-04-15       20.25
88  1993-05-15       19.95
89  1993-06-15       19.09
90  1993-07-15       17.89
91  1993-08-15       18.01
92  1993-09-15       17.50
93  1993-10-15       18.15
94  1993-11-15       16.61
95  1993-12-15       14.52
96  1994-01-15       15.03
97  1994-02-15       14.78
98  1994-03-15       14.68
99  1994-04-15       16.42
100 1994-05-15       17.89
101 1994-06-15       19.06
102 1994-07-15       19.66
103 1994-08-15       18.38
104 1994-09-15       17.45
105 1994-10-15       17.72
106 1994-11-15       18.07
107 1994-12-15       17.16
108 1995-01-15       18.04
109 1995-02-15       18.57
110 1995-03-15       18.54
111 1995-04-15       19.90
112 1995-05-15       19.74
113 1995-06-15       18.45
114 1995-07-15       17.33
115 1995-08-15       18.02
116 1995-09-15       18.23
117 1995-10-15       17.43
118 1995-11-15       17.99
119 1995-12-15       19.03
120 1996-01-15       18.86
121 1996-02-15       19.09
122 1996-03-15       21.33
123 1996-04-15       23.50
124 1996-05-15       21.17
125 1996-06-15       20.42
126 1996-07-15       21.30
127 1996-08-15       21.90
128 1996-09-15       23.97
129 1996-10-15       24.88
130 1996-11-15       23.71
131 1996-12-15       25.23
132 1997-01-15       25.13
133 1997-02-15       22.18
134 1997-03-15       20.97
135 1997-04-15       19.70
136 1997-05-15       20.82
137 1997-06-15       19.26
138 1997-07-15       19.66
139 1997-08-15       19.95
140 1997-09-15       19.80
141 1997-10-15       21.33
142 1997-11-15       20.19
143 1997-12-15       18.33
144 1998-01-15       16.72
145 1998-02-15       16.06
146 1998-03-15       15.12
147 1998-04-15       15.35
148 1998-05-15       14.91
149 1998-06-15       13.72
150 1998-07-15       14.17
151 1998-08-15       13.47
152 1998-09-15       15.03
153 1998-10-15       14.46
154 1998-11-15       13.00
155 1998-12-15       11.35
156 1999-01-15       12.52
157 1999-02-15       12.01
158 1999-03-15       14.68
159 1999-04-15       17.31
160 1999-05-15       17.72
161 1999-06-15       17.92
162 1999-07-15       20.10
163 1999-08-15       21.28
164 1999-09-15       23.80
165 1999-10-15       22.69
166 1999-11-15       25.00
167 1999-12-15       26.10
168 2000-01-15       27.26
169 2000-02-15       29.37
170 2000-03-15       29.84
171 2000-04-15       25.72
172 2000-05-15       28.79
173 2000-06-15       31.82
174 2000-07-15       29.70
175 2000-08-15       31.26
176 2000-09-15       33.88
177 2000-10-15       33.11
178 2000-11-15       34.42
179 2000-12-15       28.44
180 2001-01-15       29.59
181 2001-02-15       29.61
182 2001-03-15       27.25
183 2001-04-15       27.49
184 2001-05-15       28.63
185 2001-06-15       27.60
186 2001-07-15       26.43
187 2001-08-15       27.37
188 2001-09-15       26.20
189 2001-10-15       22.17
190 2001-11-15       19.64
191 2001-12-15       19.39
192 2002-01-15       19.72
193 2002-02-15       20.72
194 2002-03-15       24.53
195 2002-04-15       26.18
196 2002-05-15       27.04
197 2002-06-15       25.52
198 2002-07-15       26.97
199 2002-08-15       28.39
200 2002-09-15       29.66
201 2002-10-15       28.84
202 2002-11-15       26.35
203 2002-12-15       29.46
204 2003-01-15       32.95
205 2003-02-15       35.83
206 2003-03-15       33.51
207 2003-04-15       28.17
208 2003-05-15       28.11
209 2003-06-15       30.66
210 2003-07-15       30.76
211 2003-08-15       31.57
212 2003-09-15       28.31
213 2003-10-15       30.34
214 2003-11-15       31.11
215 2003-12-15       32.13
216 2004-01-15       34.31
217 2004-02-15       34.69
218 2004-03-15       36.74
219 2004-04-15       36.75
220 2004-05-15       40.28
221 2004-06-15       38.03
222 2004-07-15       40.78
223 2004-08-15       44.90
224 2004-09-15       45.94
225 2004-10-15       53.28
226 2004-11-15       48.47
227 2004-12-15       43.15
228 2005-01-15       46.84
229 2005-02-15       48.15
230 2005-03-15       54.19
231 2005-04-15       52.98
232 2005-05-15       49.83
233 2005-06-15       56.35
234 2005-07-15       59.00
235 2005-08-15       64.99
236 2005-09-15       65.59
237 2005-10-15       62.26
238 2005-11-15       58.32
239 2005-12-15       59.41
240 2006-01-15       65.49
241 2006-02-15       61.63
242 2006-03-15       62.69
243 2006-04-15       69.44
244 2006-05-15       70.84
245 2006-06-15       70.95
246 2006-07-15       74.41
247 2006-08-15       73.04
248 2006-09-15       63.80
249 2006-10-15       58.89
250 2006-11-15       59.08
251 2006-12-15       61.96
252 2007-01-15       54.51
253 2007-02-15       59.28
254 2007-03-15       60.44
255 2007-04-15       63.98
256 2007-05-15       63.46
257 2007-06-15       67.49
258 2007-07-15       74.12
259 2007-08-15       72.36
260 2007-09-15       79.92
261 2007-10-15       85.80
262 2007-11-15       94.77
263 2007-12-15       91.69
264 2008-01-15       92.97
265 2008-02-15       95.39
266 2008-03-15      105.45
267 2008-04-15      112.58
268 2008-05-15      125.40
269 2008-06-15      133.88
270 2008-07-15      133.37
271 2008-08-15      116.67
272 2008-09-15      104.11
273 2008-10-15       76.61
274 2008-11-15       57.31
275 2008-12-15       41.12
276 2009-01-15       41.71
277 2009-02-15       39.09
278 2009-03-15       47.94
279 2009-04-15       49.65
280 2009-05-15       59.03
281 2009-06-15       69.64
282 2009-07-15       64.15
283 2009-08-15       71.05
284 2009-09-15       69.41
285 2009-10-15       75.72
286 2009-11-15       77.99
287 2009-12-15       74.47
288 2010-01-15       78.33
289 2010-02-15       76.39
290 2010-03-15       81.20
291 2010-04-15       84.29
292 2010-05-15       73.74
293 2010-06-15       75.34
294 2010-07-15       76.32
295 2010-08-15       76.60
296 2010-09-15       75.24
297 2010-10-15       81.89
298 2010-11-15       84.25
299 2010-12-15       89.15
300 2011-01-15       89.17
301 2011-02-15       88.58
302 2011-03-15      102.86
303 2011-04-15      109.53
304 2011-05-15      100.90
305 2011-06-15       96.26
306 2011-07-15       97.30
307 2011-08-15       86.33
308 2011-09-15       85.52
309 2011-10-15       86.32
310 2011-11-15       97.16
311 2011-12-15       98.56
312 2012-01-15      100.27
313 2012-02-15      102.20
314 2012-03-15      106.16
315 2012-04-15      103.32
316 2012-05-15       94.66
317 2012-06-15       82.30
318 2012-07-15       87.90
319 2012-08-15       94.13
320 2012-09-15       94.51
321 2012-10-15       89.49
322 2012-11-15       86.53
323 2012-12-15       87.86
324 2013-01-15       94.76
325 2013-02-15       95.31
326 2013-03-15       92.94
327 2013-04-15       92.02
328 2013-05-15       94.51
329 2013-06-15       95.77
330 2013-07-15      104.67
331 2013-08-15      106.57
332 2013-09-15      106.29
333 2013-10-15      100.54
334 2013-11-15       93.86
335 2013-12-15       97.63
336 2014-01-15       94.62
337 2014-02-15      100.82
338 2014-03-15      100.80
339 2014-04-15      102.07
340 2014-05-15      102.18
341 2014-06-15      105.79
342 2014-07-15      103.59
343 2014-08-15       96.54
344 2014-09-15       93.21
345 2014-10-15       84.40
346 2014-11-15       75.79
347 2014-12-15       59.29
348 2015-01-15       47.22
349 2015-02-15       50.58
350 2015-03-15       47.82
351 2015-04-15       54.45
352 2015-05-15       59.27
353 2015-06-15       59.82
354 2015-07-15       50.90
355 2015-08-15       42.87
356 2015-09-15       45.48
357 2015-10-15       46.22
358 2015-11-15       42.44
359 2015-12-15       37.19
360 2016-01-15       31.68
361 2016-02-15       30.32
362 2016-03-15       37.55
363 2016-04-15       40.75
364 2016-05-15       46.71
365 2016-06-15       48.76
366 2016-07-15       44.65
367 2016-08-15       44.72
368 2016-09-15       45.18
369 2016-10-15       49.78
370 2016-11-15       45.66
371 2016-12-15       51.97
372 2017-01-15       52.50
373 2017-02-15       53.47
374 2017-03-15       49.33
375 2017-04-15       51.06
376 2017-05-15       48.48
377 2017-06-15       45.18
378 2017-07-15       46.63
379 2017-08-15       48.04
380 2017-09-15       49.82
381 2017-10-15       51.58
382 2017-11-15       56.64
383 2017-12-15       57.88
384 2018-01-15       63.70
385 2018-02-15       62.23
386 2018-03-15       62.73
387 2018-04-15       66.25
388 2018-05-15       69.98
389 2018-06-15       67.87
390 2018-07-15       70.98
391 2018-08-15       68.06
392 2018-09-15       70.23
393 2018-10-15       70.75
394 2018-11-15       56.96
395 2018-12-15       49.52
396 2019-01-15       51.38
397 2019-02-15       54.95
398 2019-03-15       58.15
399 2019-04-15       63.86
400 2019-05-15       60.83
401 2019-06-15       54.66
402 2019-07-15       57.35
403 2019-08-15       54.81
404 2019-09-15       56.95
405 2019-10-15       53.96
406 2019-11-15       57.03
407 2019-12-15       59.88
408 2020-01-15       57.52
409 2020-02-15       50.54
410 2020-03-15       29.21
411 2020-04-15       16.55
412 2020-05-15       28.56
413 2020-06-15       38.31
414 2020-07-15       40.71
415 2020-08-15       42.34
416 2020-09-15       39.63
417 2020-10-15       39.40
418 2020-11-15       40.94
419 2020-12-15       47.02
420 2021-01-15       52.00
421 2021-02-15       59.04
422 2021-03-15       62.33
423 2021-04-15       61.72
424 2021-05-15       65.17
425 2021-06-15       71.38
426 2021-07-15       72.49
427 2021-08-15       67.73
428 2021-09-15       71.65
429 2021-10-15       81.48
430 2021-11-15       79.15
431 2021-12-15       71.71
432 2022-01-15       83.22
433 2022-02-15       91.64
434 2022-03-15      108.50
435 2022-04-15      101.78
436 2022-05-15      109.55
437 2022-06-15      114.84
438 2022-07-15      101.62
439 2022-08-15       93.67
440 2022-09-15       84.26
441 2022-10-15       87.55
442 2022-11-15       84.37
443 2022-12-15       76.44
444 2023-01-15       78.12
445 2023-02-15       76.83
446 2023-03-15       73.28
447 2023-04-15       79.45
448 2023-05-15       71.58
449 2023-06-15       70.25
450 2023-07-15       76.07
451 2023-08-15       81.39
452 2023-09-15       89.43
453 2023-10-15       85.64
454 2023-11-15       77.69
455 2023-12-15       71.90
456 2024-01-15       74.15
457 2024-02-15       77.25
458 2024-03-15       81.28
459 2024-04-15       85.35
460 2024-05-15       80.02
461 2024-06-15       79.77
462 2024-07-15       81.80

In [10]:
pd.set_option('display.max_rows', None)
df2

    observation_date    INDPRO
0         1986-01-01   55.6453
1         1986-02-01   55.2634
2         1986-03-01   54.8728
3         1986-04-01   54.9350
4         1986-05-01   55.0399
5         1986-06-01   54.8260
6         1986-07-01   55.1670
7         1986-08-01   55.0726
8         1986-09-01   55.2237
9         1986-10-01   55.4589
10        1986-11-01   55.6763
11        1986-12-01   56.2078
12        1987-01-01   55.9911
13        1987-02-01   56.7373
14        1987-03-01   56.8136
15        1987-04-01   57.1850
16        1987-05-01   57.5424
17        1987-06-01   57.8502
18        1987-07-01   58.2421
19        1987-08-01   58.6784
20        1987-09-01   58.9088
21        1987-10-01   59.7008
22        1987-11-01   59.9956
23        1987-12-01   60.3246
24        1988-01-01   60.3090
25        1988-02-01   60.6122
26        1988-03-01   60.7452
27        1988-04-01   61.1080
28        1988-05-01   60.9843
29        1988-06-01   61.1615
30        1988-07-01   61.1710
31        1988-08-01   61.4771
32        1988-09-01   61.2785
33        1988-10-01   61.5488
34        1988-11-01   61.7049
35        1988-12-01   61.9851
36        1989-01-01   62.1677
37        1989-02-01   61.8916
38        1989-03-01   62.0508
39        1989-04-01   62.0289
40        1989-05-01   61.6871
41        1989-06-01   61.6857
42        1989-07-01   61.0896
43        1989-08-01   61.6847
44        1989-09-01   61.4794
45        1989-10-01   61.4014
46        1989-11-01   61.6081
47        1989-12-01   61.9588
48        1990-01-01   61.6352
49        1990-02-01   62.1951
50        1990-03-01   62.4916
51        1990-04-01   62.3511
52        1990-05-01   62.5353
53        1990-06-01   62.7479
54        1990-07-01   62.6435
55        1990-08-01   62.8704
56        1990-09-01   62.8839
57        1990-10-01   62.4973
58        1990-11-01   61.7175
59        1990-12-01   61.2885
60        1991-01-01   61.0842
61        1991-02-01   60.6387
62        1991-03-01   60.2973
63        1991-04-01   60.4524
64        1991-05-01   61.0587
65        1991-06-01   61.5514
66        1991-07-01   61.7201
67        1991-08-01   61.7289
68        1991-09-01   62.2369
69        1991-10-01   62.1718
70        1991-11-01   62.0894
71        1991-12-01   61.8060
72        1992-01-01   61.4823
73        1992-02-01   61.9192
74        1992-03-01   62.4403
75        1992-04-01   62.9199
76        1992-05-01   63.1268
77        1992-06-01   63.1624
78        1992-07-01   63.7348
79        1992-08-01   63.3802
80        1992-09-01   63.5834
81        1992-10-01   64.0178
82        1992-11-01   64.2628
83        1992-12-01   64.3599
84        1993-01-01   64.6135
85        1993-02-01   64.9262
86        1993-03-01   64.8627
87        1993-04-01   65.0423
88        1993-05-01   64.8006
89        1993-06-01   64.9476
90        1993-07-01   65.1142
91        1993-08-01   65.0421
92        1993-09-01   65.3749
93        1993-10-01   65.8630
94        1993-11-01   66.1696
95        1993-12-01   66.5531
96        1994-01-01   66.7591
97        1994-02-01   66.8019
98        1994-03-01   67.4704
99        1994-04-01   67.8707
100       1994-05-01   68.1870
101       1994-06-01   68.6450
102       1994-07-01   68.7317
103       1994-08-01   69.1882
104       1994-09-01   69.3935
105       1994-10-01   69.9576
106       1994-11-01   70.4288
107       1994-12-01   71.1273
108       1995-01-01   71.2635
109       1995-02-01   71.1758
110       1995-03-01   71.2796
111       1995-04-01   71.1538
112       1995-05-01   71.4997
113       1995-06-01   71.7327
114       1995-07-01   71.4334
115       1995-08-01   72.3723
116       1995-09-01   72.6543
117       1995-10-01   72.5336
118       1995-11-01   72.7170
119       1995-12-01   72.9638
120       1996-01-01   72.5712
121       1996-02-01   73.6207
122       1996-03-01   73.5141
123       1996-04-01   74.2491
124       1996-05-01   74.8142
125       1996-06-01   75.3726
126       1996-07-01   75.3738
127       1996-08-01   75.7557
128       1996-09-01   76.2302
129       1996-10-01   76.2157
130       1996-11-01   76.8973
131       1996-12-01   77.3772
132       1997-01-01   77.5135
133       1997-02-01   78.4255
134       1997-03-01   78.9197
135       1997-04-01   78.9848
136       1997-05-01   79.4296
137       1997-06-01   79.7971
138       1997-07-01   80.4666
139       1997-08-01   81.2825
140       1997-09-01   82.0327
141       1997-10-01   82.7656
142       1997-11-01   83.4270
143       1997-12-01   83.7840
144       1998-01-01   84.1564
145       1998-02-01   84.3066
146       1998-03-01   84.3420
147       1998-04-01   84.6339
148       1998-05-01   85.1867
149       1998-06-01   84.6809
150       1998-07-01   84.3445
151       1998-08-01   86.0816
152       1998-09-01   86.0023
153       1998-10-01   86.5910
154       1998-11-01   86.5115
155       1998-12-01   86.8615
156       1999-01-01   87.2205
157       1999-02-01   87.7260
158       1999-03-01   87.9125
159       1999-04-01   88.1082
160       1999-05-01   88.6483
161       1999-06-01   88.5903
162       1999-07-01   89.1098
163       1999-08-01   89.5007
164       1999-09-01   89.1304
165       1999-10-01   90.2709
166       1999-11-01   90.7528
167       1999-12-01   91.4784
168       2000-01-01   91.4092
169       2000-02-01   91.7245
170       2000-03-01   92.0830
171       2000-04-01   92.6659
172       2000-05-01   92.9347
173       2000-06-01   93.0018
174       2000-07-01   92.8373
175       2000-08-01   92.5910
176       2000-09-01   92.9827
177       2000-10-01   92.6400
178       2000-11-01   92.6604
179       2000-12-01   92.3457
180       2001-01-01   91.8908
181       2001-02-01   91.2851
182       2001-03-01   91.0585
183       2001-04-01   90.7384
184       2001-05-01   90.2607
185       2001-06-01   89.7811
186       2001-07-01   89.2352
187       2001-08-01   89.1570
188       2001-09-01   88.6749
189       2001-10-01   88.4051
190       2001-11-01   87.8860
191       2001-12-01   87.8518
192       2002-01-01   88.4634
193       2002-02-01   88.4578
194       2002-03-01   89.1265
195       2002-04-01   89.5507
196       2002-05-01   89.9348
197       2002-06-01   90.6736
198       2002-07-01   90.6436
199       2002-08-01   90.5505
200       2002-09-01   90.6373
201       2002-10-01   90.3988
202       2002-11-01   90.8947
203       2002-12-01   90.3906
204       2003-01-01   91.1369
205       2003-02-01   91.2505
206       2003-03-01   91.0006
207       2003-04-01   90.4311
208       2003-05-01   90.4000
209       2003-06-01   90.5196
210       2003-07-01   90.9869
211       2003-08-01   90.7933
212       2003-09-01   91.3819
213       2003-10-01   91.5049
214       2003-11-01   92.1265
215       2003-12-01   92.1732
216       2004-01-01   92.3268
217       2004-02-01   92.8995
218       2004-03-01   92.5368
219       2004-04-01   92.8957
220       2004-05-01   93.5845
221       2004-06-01   92.8651
222       2004-07-01   93.5502
223       2004-08-01   93.6301
224       2004-09-01   93.7353
225       2004-10-01   94.5695
226       2004-11-01   94.8015
227       2004-12-01   95.5415
228       2005-01-01   95.8785
229       2005-02-01   96.5709
230       2005-03-01   96.4345
231       2005-04-01   96.6347
232       2005-05-01   96.7251
233       2005-06-01   97.1483
234       2005-07-01   96.8397
235       2005-08-01   97.1584
236       2005-09-01   95.2764
237       2005-10-01   96.4411
238       2005-11-01   97.5016
239       2005-12-01   97.9723
240       2006-01-01   98.1270
241       2006-02-01   98.1687
242       2006-03-01   98.3913
243       2006-04-01   98.6826
244       2006-05-01   98.7074
245       2006-06-01   99.0398
246       2006-07-01   98.9751
247       2006-08-01   99.4047
248       2006-09-01   99.2246
249       2006-10-01   99.1229
250       2006-11-01   99.0963
251       2006-12-01  100.1125
252       2007-01-01   99.7546
253       2007-02-01  100.7166
254       2007-03-01  100.8952
255       2007-04-01  101.5723
256       2007-05-01  101.6269
257       2007-06-01  101.6547
258       2007-07-01  101.4953
259       2007-08-01  101.6943
260       2007-09-01  101.9428
261       2007-10-01  101.6446
262       2007-11-01  102.2167
263       2007-12-01  102.2764
264       2008-01-01  102.1493
265       2008-02-01  101.7756
266       2008-03-01  101.4508
267       2008-04-01  100.7554
268       2008-05-01  100.1336
269       2008-06-01   99.8728
270       2008-07-01   99.4194
271       2008-08-01   97.8491
272       2008-09-01   93.5576
273       2008-10-01   94.4985
274       2008-11-01   93.2617
275       2008-12-01   90.6266
276       2009-01-01   88.3712
277       2009-02-01   87.8430
278       2009-03-01   86.4689
279       2009-04-01   85.7903
280       2009-05-01   84.9436
281       2009-06-01   84.6746
282       2009-07-01   85.6853
283       2009-08-01   86.6393
284       2009-09-01   87.3821
285       2009-10-01   87.5809
286       2009-11-01   87.9388
287       2009-12-01   88.2404
288       2010-01-01   89.1897
289       2010-02-01   89.5046
290       2010-03-01   90.1356
291       2010-04-01   90.4607
292       2010-05-01   91.7014
293       2010-06-01   91.9033
294       2010-07-01   92.2549
295       2010-08-01   92.5936
296       2010-09-01   92.8533
297       2010-10-01   92.6033
298       2010-11-01   92.6686
299       2010-12-01   93.5916
300       2011-01-01   93.3889
301       2011-02-01   93.0045
302       2011-03-01   93.9684
303       2011-04-01   93.6571
304       2011-05-01   93.7723
305       2011-06-01   94.0493
306       2011-07-01   94.4958
307       2011-08-01   95.0974
308       2011-09-01   95.0244
309       2011-10-01   95.6891
310       2011-11-01   95.6778
311       2011-12-01   96.1809
312       2012-01-01   96.7595
313       2012-02-01   97.0662
314       2012-03-01   96.5609
315       2012-04-01   97.2510
316       2012-05-01   97.4595
317       2012-06-01   97.4768
318       2012-07-01   97.6714
319       2012-08-01   97.2734
320       2012-09-01   97.2217
321       2012-10-01   97.5311
322       2012-11-01   97.9084
323       2012-12-01   98.1884
324       2013-01-01   98.1736
325       2013-02-01   98.6434
326       2013-03-01   99.0470
327       2013-04-01   98.9445
328       2013-05-01   99.0383
329       2013-06-01   99.2221
330       2013-07-01   98.8987
331       2013-08-01   99.4897
332       2013-09-01  100.0210
333       2013-10-01   99.9037
334       2013-11-01  100.1582
335       2013-12-01  100.3740
336       2014-01-01   99.9899
337       2014-02-01  100.7471
338       2014-03-01  101.7435
339       2014-04-01  101.8273
340       2014-05-01  102.2392
341       2014-06-01  102.5774
342       2014-07-01  102.7954
343       2014-08-01  102.6322
344       2014-09-01  102.9417
345       2014-10-01  102.9611
346       2014-11-01  103.5978
347       2014-12-01  103.6151
348       2015-01-01  102.7923
349       2015-02-01  102.1366
350       2015-03-01  101.7869
351       2015-04-01  101.2255
352       2015-05-01  100.7675
353       2015-06-01  100.4588
354       2015-07-01  101.0893
355       2015-08-01  100.9165
356       2015-09-01  100.6330
357       2015-10-01  100.1563
358       2015-11-01   99.4366
359       2015-12-01   98.9471
360       2016-01-01   99.4391
361       2016-02-01   98.9232
362       2016-03-01   98.1635
363       2016-04-01   98.4775
364       2016-05-01   98.2549
365       2016-06-01   98.7315
366       2016-07-01   98.8452
367       2016-08-01   98.7427
368       2016-09-01   98.6552
369       2016-10-01   98.7237
370       2016-11-01   98.3443
371       2016-12-01   99.0406
372       2017-01-01   98.8158
373       2017-02-01   98.4356
374       2017-03-01   99.0492
375       2017-04-01  100.0416
376       2017-05-01  100.1280
377       2017-06-01  100.3370
378       2017-07-01  100.0865
379       2017-08-01   99.6323
380       2017-09-01   99.7482
381       2017-10-01  100.9893
382       2017-11-01  101.2493
383       2017-12-01  101.4871
384       2018-01-01  101.4852
385       2018-02-01  101.7319
386       2018-03-01  102.1943
387       2018-04-01  103.3551
388       2018-05-01  102.3810
389       2018-06-01  103.2256
390       2018-07-01  103.3561
391       2018-08-01  104.0585
392       2018-09-01  104.1038
393       2018-10-01  103.9297
394       2018-11-01  104.0126
395       2018-12-01  104.0451
396       2019-01-01  103.3598
397       2019-02-01  102.8251
398       2019-03-01  102.8361
399       2019-04-01  102.2748
400       2019-05-01  102.4176
401       2019-06-01  102.5425
402       2019-07-01  102.0057
403       2019-08-01  102.7814
404       2019-09-01  102.4601
405       2019-10-01  101.5878
406       2019-11-01  102.1494
407       2019-12-01  101.9421
408       2020-01-01  101.3372
409       2020-02-01  101.6718
410       2020-03-01   97.6060
411       2020-04-01   84.6812
412       2020-05-01   86.0108
413       2020-06-01   91.6745
414       2020-07-01   95.0037
415       2020-08-01   95.9294
416       2020-09-01   95.8914
417       2020-10-01   96.5256
418       2020-11-01   96.9529
419       2020-12-01   98.2039
420       2021-01-01   98.8135
421       2021-02-01   95.5072
422       2021-03-01   98.1929
423       2021-04-01   98.3317
424       2021-05-01   99.1867
425       2021-06-01   99.6483
426       2021-07-01  100.0668
427       2021-08-01  100.0412
428       2021-09-01   98.9955
429       2021-10-01  100.3542
430       2021-11-01  101.2684
431       2021-12-01  101.1948
432       2022-01-01  101.2146
433       2022-02-01  101.8458
434       2022-03-01  102.6732
435       2022-04-01  102.9024
436       2022-05-01  102.9659
437       2022-06-01  102.8224
438       2022-07-01  103.0505
439       2022-08-01  103.1703
440       2022-09-01  103.5326
441       2022-10-01  103.4442
442       2022-11-01  103.1058
443       2022-12-01  101.8266
444       2023-01-01  102.7476
445       2023-02-01  102.8003
446       2023-03-01  102.8143
447       2023-04-01  103.2241
448       2023-05-01  102.9809
449       2023-06-01  102.3809
450       2023-07-01  103.0722
451       2023-08-01  103.0951
452       2023-09-01  103.3081
453       2023-10-01  102.5781
454       2023-11-01  102.8868
455       2023-12-01  102.6309
456       2024-01-01  101.4830
457       2024-02-01  102.7267
458       2024-03-01  102.5001
459       2024-04-01  102.4955
460       2024-05-01  103.2734
461       2024-06-01  103.5494
462       2024-07-01  102.8887

In [5]:
df1.shape

(463, 2)

In [6]:
df2.shape

(463, 2)

In [7]:
df2.head()

  observation_date   INDPRO
0       1986-01-01  55.6453
1       1986-02-01  55.2634
2       1986-03-01  54.8728
3       1986-04-01  54.9350
4       1986-05-01  55.0399

In [11]:
wti_missing_values = df1.isnull().sum()
print(wti_missing_values)

Date          0
Spot Price    0
dtype: int64

In [12]:
df1['Normalized_Spot_Price'] = (df1['Spot Price'] - df1['Spot Price'].min()) / (df1['Spot Price'].max() - df1['Spot Price'].min())

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

# Assume your data has additional features; here, we'll focus on the normalized Spot Price.
X = df1[['Normalized_Spot_Price']]  # Replace with actual features if available
y = df1['Spot Price']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Apply LASSO regression
lasso = Lasso(alpha=0.01)  # Adjust alpha to control regularization strength
lasso.fit(X_train_scaled, y_train)

# Get the coefficients
lasso_coefficients = lasso.coef_

# Identify the selected features
selected_features = X.columns[lasso_coefficients != 0]

print("Selected Features:", selected_features)

Selected Features: Index(['Normalized_Spot_Price'], dtype='object')

In [14]:
import pmdarima as pm
from sklearn.metrics import mean_squared_error
import numpy as np

# Fit ARIMA model
arima_model = pm.auto_arima(y_train, seasonal=False, trace=True, suppress_warnings=True)

# Forecasting on the test data
y_pred_arima = arima_model.predict(n_periods=len(y_test))

# Evaluate the ARIMA model
arima_rmse = np.sqrt(mean_squared_error(y_test, y_pred_arima))
print("ARIMA RMSE:", arima_rmse)

ModuleNotFoundError: No module named 'pmdarima'

In [15]:
!pip install pmdarima
import pmdarima as pm
from sklearn.metrics import mean_squared_error
import numpy as np

# Fit ARIMA model
arima_model = pm.auto_arima(y_train, seasonal=False, trace=True, suppress_warnings=True)

# Forecasting on the test data
y_pred_arima = arima_model.predict(n_periods=len(y_test))

# Evaluate the ARIMA model
arima_rmse = np.sqrt(mean_squared_error(y_test, y_pred_arima))
print("ARIMA RMSE:", arima_rmse)

Collecting pmdarima
  Downloading pmdarima-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (1.4.2)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (3.0.11)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (2.1.4)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (1.3.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (1.13.1)
Requirement already satisfied: statsmodels>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (0.14.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (2.0.7)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (71.0.4)
Requirement already satisfied: packaging>=17.1 in /usr/local/lib/python3.10/dist-packages (from pmdarima) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pmdarima) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pmdarima) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19->pmdarima) (2024.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22->pmdarima) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.13.2->pmdarima) (0.5.6)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels>=0.13.2->pmdarima) (1.16.0)
Downloading pmdarima-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 22.4 MB/s eta 0:00:00
Installing collected packages: pmdarima
Successfully installed pmdarima-2.0.4
Performing stepwise search to minimize aic
 ARIMA(2,0,2)(0,0,0)[0]             : AIC=inf, Time=0.97 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=4040.422, Time=0.05 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=3770.652, Time=0.07 sec
 ARIMA(0,0,1)(0,0,0)[0]             : AIC=3905.580, Time=0.93 sec
 ARIMA(2,0,0)(0,0,0)[0]             : AIC=3691.425, Time=0.13 sec
 ARIMA(3,0,0)(0,0,0)[0]             : AIC=3653.713, Time=0.06 sec
 ARIMA(4,0,0)(0,0,0)[0]             : AIC=3647.671, Time=0.11 sec
 ARIMA(5,0,0)(0,0,0)[0]             : AIC=3645.392, Time=0.12 sec
 ARIMA(5,0,1)(0,0,0)[0]             : AIC=inf, Time=1.03 sec
 ARIMA(4,0,1)(0,0,0)[0]             : AIC=inf, Time=0.84 sec
 ARIMA(5,0,0)(0,0,0)[0] intercept   : AIC=3577.455, Time=0.18 sec
 ARIMA(4,0,0)(0,0,0)[0] intercept   : AIC=3577.652, Time=0.16 sec
 ARIMA(5,0,1)(0,0,0)[0] intercept   : AIC=3579.447, Time=0.38 sec
 ARIMA(4,0,1)(0,0,0)[0] intercept   : AIC=3579.594, Time=0.46 sec

Best model:  ARIMA(5,0,0)(0,0,0)[0] intercept
Total fit time: 5.538 seconds
ARIMA RMSE: 27.298496060823133

/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

In [16]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Reshape data for LSTM [samples, time steps, features]
X_train_reshaped = np.reshape(X_train_scaled, (X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_reshaped = np.reshape(X_test_scaled, (X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

# Build LSTM model
model_lstm = Sequential()
model_lstm.add(LSTM(units=50, return_sequences=True, input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2])))
model_lstm.add(LSTM(units=50))
model_lstm.add(Dense(1))

model_lstm.compile(optimizer='adam', loss='mean_squared_error')

# Train LSTM model
model_lstm.fit(X_train_reshaped, y_train, epochs=100, batch_size=32)

# Predict and evaluate
y_pred_lstm = model_lstm.predict(X_test_reshaped)
lstm_rmse = np.sqrt(mean_squared_error(y_test, y_pred_lstm))
print("LSTM RMSE:", lstm_rmse)

Epoch 1/100

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

12/12 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 3285.4797
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3357.7385
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3029.1008
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3352.2654
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3054.1675
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3206.1633
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3138.9734
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2983.0559
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3003.4312
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2681.1155
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2679.6230
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2578.8254
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2438.8018
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2400.7578
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2353.8540
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2226.3037
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2125.6709
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1928.3134
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2022.0637
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1903.7959
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1936.7520
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1808.4803
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1740.3556
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1686.5822
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1733.1620
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1569.6545
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1693.5133
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1432.5419
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1464.4911
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1457.0042
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1348.1190
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1353.0803
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1315.8710
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1256.3756
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1295.4558
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1185.2423
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1161.7678
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1227.7089
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1190.7714
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1245.6663
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1158.0735
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1122.4174
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1205.9888
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1124.4150
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1147.9989
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1045.5707
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 986.8427
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1061.3738
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1132.8442
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1107.5957
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 959.2036
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 999.9250
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1037.1078
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 993.0510
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 880.0640
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 976.2040
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 821.7567
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 863.6870
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 983.7220
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 875.4919
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 865.8793
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 733.6796
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 851.3245
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 898.3408
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 716.3563
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 774.9927
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 780.2625
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 764.9822
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 713.6674
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 737.4189
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 701.8557
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 621.2410
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 697.3245
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 684.8542
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 697.8154
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 591.0633
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 598.9529
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 621.8555
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 643.1697
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 597.9144
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 532.3508
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 619.3816
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 547.6714
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 619.2762
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 551.3962
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 530.9930
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 660.1190
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 494.9345
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 552.2065
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 674.0834
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 539.8669
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 535.1333
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 498.3150
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 565.1617
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 495.2831
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 540.7991
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 434.1197
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 553.2148
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 483.2607
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 480.1853
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 164ms/step
LSTM RMSE: 17.779442637040383

In [17]:
from keras.layers import Conv1D, MaxPooling1D, Flatten

# Build CNN model
model_cnn = Sequential()
model_cnn.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2])))
model_cnn.add(MaxPooling1D(pool_size=2))
model_cnn.add(Flatten())
model_cnn.add(Dense(50, activation='relu'))
model_cnn.add(Dense(1))

model_cnn.compile(optimizer='adam', loss='mean_squared_error')

# Train CNN model
model_cnn.fit(X_train_reshaped, y_train, epochs=100, batch_size=32)

# Predict and evaluate
y_pred_cnn = model_cnn.predict(X_test_reshaped)
cnn_rmse = np.sqrt(mean_squared_error(y_test, y_pred_cnn))
print("CNN RMSE:", cnn_rmse)

Epoch 1/100

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

ValueError: Exception encountered when calling Conv1D.call().

Negative dimension size caused by subtracting 2 from 1 for '{{node sequential_1_1/conv1d_1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](sequential_1_1/conv1d_1/convolution/ExpandDims, sequential_1_1/conv1d_1/convolution/ExpandDims_1)' with input shapes: [?,1,1,1], [1,2,1,64].

Arguments received by Conv1D.call():
  • inputs=tf.Tensor(shape=(None, 1, 1), dtype=float32)

In [18]:
from keras.layers import Conv1D, MaxPooling1D, Flatten

# Build CNN model
model_cnn = Sequential()
model_cnn.add(Conv1D(filters=64, kernel_size=1, activation='relu', input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2]))) # kernel_size changed to 1
model_cnn.add(MaxPooling1D(pool_size=1)) # pool_size changed to 1
model_cnn.add(Flatten())
model_cnn.add(Dense(50, activation='relu'))
model_cnn.add(Dense(1))

model_cnn.compile(optimizer='adam', loss='mean_squared_error')

# Train CNN model
model_cnn.fit(X_train_reshaped, y_train, epochs=100, batch_size=32)

# Predict and evaluate
y_pred_cnn = model_cnn.predict(X_test_reshaped)
cnn_rmse = np.sqrt(mean_squared_error(y_test, y_pred_cnn))
print("CNN RMSE:", cnn_rmse)

Epoch 1/100

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3517.8264
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3130.5886
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3074.1912
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3052.3464
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2728.5945
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2685.6177
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2648.2129
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2508.8801
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2256.1470
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1879.2140
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1638.7377
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1243.8447
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 886.2938
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 675.1612
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 382.7865
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 198.0973
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 97.5063
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50.7588
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.0810
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.5925
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20.4389
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3940
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.5299
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.7156
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.0925
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14.7207
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15.0190
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4659
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.9460
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8973
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8578
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.2603
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4200
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1756
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0783
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1082
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5870
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1421
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8244
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.6122
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.3045
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.8212
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.7754
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.8808
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.5407
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.6492
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.2520
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.0947
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.7194
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.4579
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.4447
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2760
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.8791
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5962
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5380
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3604
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2906
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1483
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9645
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9166
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8044
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6633
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6196
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5883
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4564
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5456
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4019
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4902
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3182
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3520
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3277
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3845
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3465
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3109
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2726
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2781
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2167
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2415
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2106
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2326
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1755
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2214
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1574
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1491
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1755
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1528
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1481
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1329
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1232
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1178
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1200
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0996
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1119
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1186
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0890
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0850
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0824
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0862
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0721
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0796
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
CNN RMSE: 0.36207395109779306

In [20]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from textblob import TextBlob

# Assume `geopolitical_data` is a DataFrame containing text data related to geopolitical events
# Ensure both 'Date' and 'Text' lists have the same number of elements
geopolitical_data = pd.DataFrame({
    'Date': ['2024-01-01', '2024-02-01'], # Add more dates if needed
    'Text': ['Oil embargo announced...', 'Conflict escalates in...'] # Add more text if needed
})

# Preprocess text data
def preprocess_text(text):
    # Example preprocessing
    text = text.lower()
    text = ''.join([c for c in text if c.isalpha() or c.isspace()])
    return text

geopolitical_data['Cleaned_Text'] = geopolitical_data['Text'].apply(preprocess_text)

# Feature extraction using TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=100)
tfidf_features = tfidf_vectorizer.fit_transform(geopolitical_data['Cleaned_Text']).toarray()

# Sentiment analysis
geopolitical_data['Sentiment'] = geopolitical_data['Cleaned_Text'].apply(lambda x: TextBlob(x).sentiment.polarity)

# Combine TF-IDF features with sentiment
geopolitical_features = pd.DataFrame(tfidf_features)
geopolitical_features['Sentiment'] = geopolitical_data['Sentiment']

# Dimensionality reduction (optional)
pca = PCA(n_components=10)
geopolitical_features_reduced = pca.fit_transform(geopolitical_features)

# Merge with the main WTI dataset on Date
# Make sure you have a DataFrame named 'wti_data' with a 'Date' column
# wti_data_with_geo = wti_data.merge(geopolitical_data[['Date']], on='Date', how='left')

# Add the new features to the dataset
# wti_data_with_geo = pd.concat([wti_data_with_geo, pd.DataFrame(geopolitical_features_reduced)], axis=1)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.

In [21]:
# ... (previous code)

# Convert column names to strings
geopolitical_features.columns = geopolitical_features.columns.astype(str)

# Dimensionality reduction (optional)
pca = PCA(n_components=10)
geopolitical_features_reduced = pca.fit_transform(geopolitical_features)

# ... (rest of the code)

ValueError: n_components=10 must be between 0 and min(n_samples, n_features)=2 with svd_solver='full'

In [19]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from textblob import TextBlob

# Assume `geopolitical_data` is a DataFrame containing text data related to geopolitical events
geopolitical_data = pd.DataFrame({
    'Date': ['2024-01-01', '2024-02-01', ...],
    'Text': ['Oil embargo announced...', 'Conflict escalates in...']
})

# Preprocess text data
def preprocess_text(text):
    # Example preprocessing
    text = text.lower()
    text = ''.join([c for c in text if c.isalpha() or c.isspace()])
    return text

geopolitical_data['Cleaned_Text'] = geopolitical_data['Text'].apply(preprocess_text)

# Feature extraction using TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=100)
tfidf_features = tfidf_vectorizer.fit_transform(geopolitical_data['Cleaned_Text']).toarray()

# Sentiment analysis
geopolitical_data['Sentiment'] = geopolitical_data['Cleaned_Text'].apply(lambda x: TextBlob(x).sentiment.polarity)

# Combine TF-IDF features with sentiment
geopolitical_features = pd.DataFrame(tfidf_features)
geopolitical_features['Sentiment'] = geopolitical_data['Sentiment']

# Dimensionality reduction (optional)
pca = PCA(n_components=10)
geopolitical_features_reduced = pca.fit_transform(geopolitical_features)

# Merge with the main WTI dataset on Date
wti_data_with_geo = wti_data.merge(geopolitical_data[['Date']], on='Date', how='left')

# Add the new features to the dataset
wti_data_with_geo = pd.concat([wti_data_with_geo, pd.DataFrame(geopolitical_features_reduced)], axis=1)

ValueError: All arrays must be of the same length